planetlabs/draino

cmd/draino/draino.go

Apparently I temporarily forgot how switches work in Go.

Pod eviction filter flags should not be mutually exclusive

---

README.md
cmd/draino/draino.go

This commit drops the node label, which can introduce high cardinality, and renames the labels to follow the thing_unit_total metric name that is considered a best practice per https://prometheus.io/docs/practices/naming/#metric-names

Be better Prometheus citizens

---

.travis.yml

This is a follow on from https://github.com/planetlabs/draino/pull/18, which updated the Docker build but not the Travis tests.
We should probably consider running the tests in a Docker container for environmental consistency at some point.

Migrate Travis tests to dep, too

---

README.md
manifest.yml
scripts/build.sh
scripts/push.sh

This gets our draino images publishing to the planetlabs org instead of @negz personal dockerhub. I'll be making the requisite changes to our travis builds once their support folks respond to my request to migrate the build from travis-ci.org to travis-ci.com.

repoint dockerhub assets to planetlabs

---

scripts/build.sh

Just build it once and retag the latest image using the VERSION just built. Also fail the script on errors.

don't build the image twice

---

Gopkg.lock
cmd/draino/draino.go

I had intended this argument to be mandatory, but neglected to realise that args needed the 'Required' flag to make them so. This could affect an obscure use case in which folks are using Draino to drain all nodes with a particular label regardless of node condition. That behaviour could be reproduced after this change by explicitly running Draino with a condition applicable to all nodes you wish to drain, i.e. `Ready`.
This should act as a safety to avoid the situation observed in #29 in which starting Draino with no labels or conditions specified (i.e. starting it with no arguments) will schedule all nodes in the cluster for draining.
Fixes #29.

Make node conditions mandatory

---

cmd/draino/draino.go

Some folks would like to see some log output to sanity that draino has started up.

add a simple log line prior to main run loop

---

internal/kubernetes/drainer.go
internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go

The attribute LastTransitionTime of NodeCondition indicates that last
time the condition transit from one status to another, so it's very
useful to be leveraged to track how long a node is in a particular
state.
Meanwhile, a new backward-compatible condition format is introduced
so support more values and the status duration for condition as below:
OutOfDisk=True,10m
That means when condition OutOfDisk equals True and the state needs
to be on that status at least 10 mins. And the old format is still
supported. When a simple condition, e.g. KernelDeadlock, is passed in,
it will be parsed as *KernelDeadlock=True,0* to keep the backward
compatibility.
Note that the value after comma can be any string which can be parsed
by time.ParseDuration, e.g. 30s, 10m, etc.
fixes #33

Support more values and status duration for condition

---

helm/draino/templates/deployment.yaml

The `initialDelaySeconds` entry should be configured inside the `livenessProbe` entry and not inside `httpGet`. Trying to apply the helm chart as it was would cause an error similar to:
```
error: error validating "deployment.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe.httpGet): unknown field "initialDelaySeconds" in io.k8s.api.core.v1.HTTPGetAction; if you choose to ignore these errors, turn validation off with --validate=false
```
This PR simply moves `initialDelaySeconds` to the right place.

helm: fix indentation level for initialDelaySeconds in probe

---

Gopkg.lock
cmd/draino/draino.go
helm/draino/templates/clusterrole.yaml

This PR fixes the issue #39 by implementing leader election for the node watcher and its handlers.
A non-leader process will freeze waiting for it to become leader before starting the node watcher. If we loose an election after we're already leader we'll simply kill the process and let kubernetes restart it, this is a common pattern seen in controllers in the wild.
The web server handler is started before leader election to allow metrics and healthcheck even for non-leaders.
Closes #39

Add leader election to ensure only one node handler is running

---

internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go

If the --node-label=KEY=VALUE  comes with a VALUE that is empty the node selection is failing and return all nodes. This PR limits the scope to the node that hold a label with the given KEY with an empty VALUE.

take into account key/value with empty value for node label selector

---

Dockerfile

Container builds have been failing since 26dcd6b2. Somewhat easy to miss in MR's because we don't build until master.

correction to addgroup / user

---

helm/draino/templates/deployment.yaml
helm/draino/values.yaml

This Pull Request updates the default image tag to the latest at this moment and also adds a new value `securityContext`, so users can customize draino to run as non-root properly.
The default securityContext parameters are working out-of-box with the specified image tag, `2c3d2b4 `, so there are no breaking changes.
It is also important from the security perspective, as now drain will run as non-root.

[helm] Add securityContext and update default image tag

---

README.md
cmd/draino/draino.go

protected pod against eviction with system known annotation

---

cmd/draino/draino.go

Fixes https://github.com/planetlabs/draino/issues/79
Summary:
- Draino uses k8s.io/api and k8s.io/apimachinery which both import k8s.io/klog
- By default klog writes logs to tmp files (unless initialized properly)
- klog has an init function that replaces writing to log files with stderr globally (InitFlags)

initalize klog properly

---

helm/draino/values.yaml

Now that https://github.com/planetlabs/draino/pull/80 is merged, we can harden the deployment even more

Make unprivileged and immutable

---

.travis.yml
helm/draino/templates/deployment.yaml
helm/draino/values.yaml

The `privileged` and `readOnlyRootFilesystem` fields recently added to the Helm chart are not valid in the pod's security context and can only be used in the container's security context. Trying to apply the generated resource would cause the error:
```
error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "privileged" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "readOnlyRootFilesystem" in io.k8s.api.core.v1.PodSecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false
```
This PR creates a new section in the helm values for container specific security context flags. It also includes a new CI job to validate helm generated …

Move invalid pod security context fields in helm chart to container security context

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/eventhandler.go

This commit fixes a data race when calling HasSchedule. This happens because the `time.AfterFunc` function is called by a new goroutine and it updates fields which may be read in parallel by `HasSchedule`.
A new test was added to more easily trigger the data race condition however it also happens during normal draino operation because the event handler may call `HasSchedule` multiple times for an already scheduled node.
The `running` return value from `HasSchedule` was removed to simplify the code as it wasn't used anywhere.
Data race sample:
```
$ go test -race
Now: 2020-08-20T11:00:04-03:00
==================
WARNING: DATA RACE
Write at 0x00c00026c098 by goroutine 15:
github.com/planetlabs/draino/internal/kubernetes.(*DrainSchedules).newSchedule.func1() …
```

Fix data race in drain scheduler

---

cmd/draino/draino.go
go.mod

In some cases we may have to run multiple draino because we need different configuration. (See #62)
In case the different instances run in the same namespace they may conflict on the leader election token.
This PR allows to specify a name for the leaderElection lock resource via program parameter.

leaderElection token name as parameter

---

.travis.yml

* Increase GC frequency: https://golangci-lint.run/usage/performance/#memory-usage
* Halve the concurrency from its default of 8.

tune golang-ci lint for travis

---

README.md
scripts/build.sh
scripts/push.sh

Using `:latest` is often an anti-pattern so lets nip it now. There are a
few MR's that have been in the bike-shed due to concerns of regressions.
Given what `draino` does, a bug that makes it through review,
testing, and lands on an unsuspecting cluster, would be painful.

remove draino:latest builds

---

Dockerfile
helm/draino/templates/clusterrole.yaml
internal/kubernetes/podfilters.go

Kubernetes stopped serving (removed) extensions apigroup for DaemonSet resource, since v1.16.0 release, which is almost since a year.
DaemonSets are available under apps/v1 groups since v1.9.0 release. So, this should work on both older clusters and also newer clusters without extensions/v1 group.
@jacobstr

use apps/v1 apigroup for DaemonSets

---

helm/draino/values.yaml

Issue: https://github.com/planetlabs/draino/issues/100
Current default image tag has `read-only file system` issues as described in issue.

update draino helm image tag

---

cmd/draino/draino.go
internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go

Fix #107
Draino will exit with error and not fail silently if the same key is provided twice in the `node-label` parameter that does a AND in case it is provided multiple times.

fail to start if node-label is provided twice with the same key - issue #107
